In [45]:
from scipy import sparse
import pandas as pd
import pickle 
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [3]:
csr_data = sparse.load_npz("file_name.npz")
user_item_matrix = pd.read_csv('user_item.csv')
knn = pickle.load(open('knnpickle_file', 'rb'))

In [6]:
user_item_matrix = user_item_matrix.drop("Unnamed: 0", axis=1)

In [40]:
user_item_matrix.head()

,movieId,12,24,34,43,46,49,56,62,65,...,270795,270807,270828,270850,270857,270859,270871,270879,270887,270896
0,5,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,3.0,0.0,3.0,1.5,0.0,0.0,0.0,0.0
1,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
3,16,4.0,3.0,5.0,0.0,3.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0
4,17,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [39]:
user_item_matrix.drop('movieId', axis=1)

,12,24,34,43,46,49,56,62,65,68,...,270795,270807,270828,270850,270857,270859,270871,270879,270887,270896
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,3.0,1.5,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
3,4.0,3.0,5.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0
4,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2636,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
csr_data = csr_matrix(user_item_matrix.drop('movieId', axis=1).values)

In [46]:
knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute', n_neighbors = 20, n_jobs = -1)
knn.fit(csr_data)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=20)

In [25]:
model.labels_[:30]

array([62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
       62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62])

In [51]:
movie_index = user_item_matrix[user_item_matrix['movieId'] == 12].index[0]

In [53]:
movie_index

1

In [54]:
distances, indices = knn.kneighbors(csr_data[movie_index], n_neighbors = 4)

In [56]:
indices_list = indices.squeeze().tolist()

In [57]:
indices_list

[1, 155, 248, 288]

In [61]:
user_item_matrix.iloc[248]['movieId']

637.0

In [62]:
csr_data

<2641x29051 sparse matrix of type '<class 'numpy.float64'>'
	with 3123382 stored elements in Compressed Sparse Row format>

In [63]:
from scipy import sparse
sparse.save_npz("csr_data.npz", csr_data)